config/routes.rb
Rails.application.routes.draw do

  root 'test_pages#home'
  get '/qwertyuiop', to: 'ngos#new'

  get '/home',      to: 'test_pages#help'
  get '/about',     to: 'test_pages#about'
  get '/contact',     to: 'test_pages#contact'
  
  get '/partners',   to: 'ngos#index'
  get '/addproject', to: 'projects#new'
  
  get '/ngos/*id/donate', to: 'ngos#donate', as: 'ngos_donate'
  post '/donate/makepayment',     to: 'ngos#make_donation'
  
  resources :projects, :except => [:new, :index]
  resources :ngos, :except => [:new]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ngo.rb
class Ngo < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ngos_controller.rb
class NgosController < ApplicationController
  def new
    @ngo = Ngo.new
  end
  
  def index
    @ngos = Ngo.all
  end
  
  def show
    @ngo = Ngo.find(params[:id])
  end
  
  def create
    @ngo = Ngo.new(ngo_params)
    if @ngo.save
      flash[:success] = "New NGO Added!"
      redirect_to @ngo
    else
      render 'new'
    end
  end
  
  def donate
    @ngo = Ngo.find(params[:id])
  end
  
  def make_donation

    tokenInput = TokenCreateInput.new
    tokenInput.number = params["card_number"]
    tokenInput.exp_month = params["expiration"].split('/')[0].to_i
    tokenInput.exp_year = params["expiration"].split('/')[1].to_i
    tokenInput.cvc = params["cvc"]
    tokenInput.billing = {
      :line1 => nil,
      :line2 => nil,
      :city => nil,
      :state => nil,
      :postal_code => nil,
      :country => nil,
      :name => params["name"],
      :email => nil,
      :phone => nil
    }
    
    token = TokenObject.new
    if token.create(tokenInput) == false
      p "failed token create"
      #failed
      flash[:danger] = token.errors[0]["detail"]
      redirect_to action: 'donate', id: params["from_ngo"]
      return
    end
    
    paymentInput = PaymentCreateInput.new
    paymentInput.amount = params["amount"].to_i*100
    paymentInput.currency = "PHP"
    paymentInput.source = {
    				"id" => token.id,
    				"type" => "token"
    			}
    paymentInput.description = "Donation to " + Ngo.find(params["from_ngo"]).name + " | " + "Name: " + params["name"] + " | " + "Phone: " + params["phone_number"] + " | " + "TIN: " + params["tin"] +  " | " + "Address: " + params["address"]
    paymentInput.statement_descriptor = "Donataion"
    
    payment = PaymentObject.new
    
    if payment.create(paymentInput) == false
      p "failed payment create"
      #failed
      flash[:danger] = payment.errors[0]["detail"]
      redirect_to action: 'donate', id: params["from_ngo"]
      return
    end

    if Ngo.find(params["from_ngo"]).name == "The University of the Philippines Foundation, Inc."
      p "UP"
      deduction = params["amount"].to_i.*1.50
    else
      p "not UP"
      deduction = params["amount"].to_i
    end
    
    flash[:success] = "SUCCESS. Donated to " + Ngo.find(params["from_ngo"]).name + "." +
                      " Your taxable income will decrease by " + deduction.to_s +
                      " Pesos! Please expect your Certificate of Donation in 30 days. Your accountant will file this along with your tax return to validate your tax deduction."
                      
    redirect_to action: 'show', id: params["from_ngo"]

    
  end

  private

    def ngo_params
      params.require(:ngo).permit(:name, :bir_cert_no, :description)
    end
    
    
    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = "New Project Added!"
      redirect_to @project
    else
      render 'new'
    end
  end

  private

    def project_params
      params.require(:project).permit(:name, :short_desc, :description)
    end
    
end

app/controllers/test_pages_controller.rb
class TestPagesController < ApplicationController
  def home
    @ngos = Ngo.all
  end

  def about
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Caritax"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

class TokenCreateInput
  attr_accessor :number, :exp_month, :exp_year, :cvc, :billing
  
  def initialize
    @number = nil
    @exp_month = nil
    @exp_year = nil
    @cvc = nil
    @billing = {
      :line1 => nil,
      :line2 => nil,
      :city => nil,
      :state => nil,
      :postal_code => nil,
      :country => nil,
      :name => nil,
      :email => nil,
      :phone => nil
    }
  end
  
end

class PaymentCreateInput
  attr_accessor :amount, :currency, :description, :source, :statement_descriptor
  
  def initialize
    @amount = nil
    @currency = nil
    @description = nil
    @source = {
      :id => nil,
      :type => nil
    }
    @statement_descriptor = nil
  end
  
end

class TokenObject
  attr_accessor :valid, :id, :errors
  
  def initialize
    @valid = false
    @id = nil
    @errors = nil
  end
  
  def create(input)
    
    if input.class != TokenCreateInput
      return false
    end
    
    require 'net/http'
    
    uri = URI("https://api.paymongo.com/v1/tokens/") 
    http = Net::HTTP.new(uri.host, uri.port)

    http.use_ssl = true
    req = Net::HTTP::Post.new(uri.path, {'Content-Type' =>'application/json'})
    req.basic_auth 'sk_live_QpCoow6boLqrY6e8jWJori4U', 'pass'
    req.body = {
    	"data" => {
    		"attributes" => {
    			"number" => input.number,
    			"exp_month" => input.exp_month.to_i,
    			"exp_year" => input.exp_year.to_i,
    			"cvc" => input.cvc.to_str		
    		}
    	}
    }.to_json
    
    resp = http.request(req)
    
    if resp.kind_of? Net::HTTPSuccess
      #update object
      @id = (JSON.parse resp.body)["data"]["id"]
      @valid = true
      @errors = nil
      return true
    else
      @errors = (JSON.parse resp.body)["errors"]
      return false
    end

  end
  
  def valid?
    return @valid
  end
end

class PaymentObject
  attr_accessor :amount, :billing, :created, :currency, :description,
    :external_reference_number, :fee, :livemode, :net_amount,
    :statement_descriptor, :status, :errors
    
  def initialize
    @amount = nil
    @billing = nil
    @created = nil
    @currency = nil
    @description = nil
    @external_reference_number = nil
    @fee = nil
    @livemode = nil
    @net_amount = nil
    @statement_descriptor = nil
    @status = nil
    @errors = nil
  end
  
  def create(input)
    
    if input.class != PaymentCreateInput
      return false
    end
    
    require 'net/http'
    
    uri = URI("https://api.paymongo.com/v1/payments") 
    http = Net::HTTP.new(uri.host, uri.port)
    
    http.use_ssl = true
    req = Net::HTTP::Post.new(uri.path, {'Content-Type' =>'application/json'})
    req.basic_auth 'sk_live_QpCoow6boLqrY6e8jWJori4U', 'pass'
    req.body = {
    	"data" => {
    		"attributes" => {
    			"amount" => input.amount.to_i,
    			"currency" => input.currency,
    			"description" => input.description,
    			"source" => input.source,
    			"statement_descriptor" => input.statement_descriptor
    		}
    	}
    }.to_json
    
    resp = http.request(req)
    data = JSON.parse resp.body
    
    if resp.kind_of? Net::HTTPSuccess
      #update object
      @amount = data["amount"]
      @billing = data["billing"]
      @created = data["created"]
      @currency = data["currency"]
      @description = data["description"]
      @external_reference_number = data["external_reference_number"]
      @fee = data["fee"]
      @livemode = data["livemode"]
      @net_amount = data["net_amount"]
      @status = data["status"]
      @errors = nil
      return true
    else
      @errors = (JSON.parse resp.body)["errors"]
      return false
    end
    
  end
  
end

app/helpers/ngos_helper.rb
module NgosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/test_pages_helper.rb
module TestPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © Buwis Information Technology, Inc. <br> EIN 30-1147902
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "CARITAX", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right" style="bg-color: #FFFFFF">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Explore",    '#' %></li>
        <li><%= link_to "Partners",    partners_path %></li>
        <li><%= link_to "Updates",    '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/ngos/donate.html.erb
<div class="row">
  
  <div class="col-md-6 col-md-offset-3">
    <h3>Donate to <%=@ngo.name %></h3>
    
    <%= form_with(url: donate_makepayment_path, method: "post") do |f| %>

      <%= f.hidden_field :from_ngo, value: params[:id] %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', :required => true %>
      
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control', :required => true %>
      
      
      <%= f.label "TIN" %>
      <%= f.text_field :tin, class: 'form-control' %>
      
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control', :required => true %>
      
      <%= f.label "Amount in pesos" %>
      <%= f.number_field :amount, pattern: "[0-9]{10}", class: 'form-control', :required => true %>
      
      <%= f.label :card_number %>
      <%= f.number_field :card_number, pattern: "[0-9]{19}", class: 'form-control', :required => true %>

      <%= f.label :expiration %>
      <%= f.text_field :expiration, class: 'form-control', :required => true %>

      <%= f.label :cvc %>
      <%= f.number_field :cvc, pattern: "[0-9]{3}", class: 'form-control', :required => true %>

      <%= f.submit "Donate", class: "btn btn-primary" %>
    <% end %>
    
    <br>
    
    <%= link_to 'Back', ngo_path, method: :get %>
  </div>
  
</div>

app/views/ngos/index.html.erb
<% provide(:title, "Partners") %>
<h1>Our Partners</h1>

<% @ngos.each do |ngo| %>
  <div>
    <h3><%= ngo.name %></h3>
    <%= link_to 'Show', ngo %>
      
  </div>
    
<% end %>

app/views/ngos/new.html.erb
<% provide(:title, 'New NGO') %>
<h1>Add NGO</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@ngo, url: "/ngos", method: "post") do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label "BIR Certification Number" %>
      <%= f.text_field :bir_cert_no, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.submit "Add NGO", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/ngos/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @ngo.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format(@ngo.description) %>
</p>

<p>
  <strong>BIR Certification Number:</strong>
  <%= @ngo.bir_cert_no %>
</p>

<%= button_to 'Donate', ngos_donate_path, method: :get, class: "btn btn-primary" %>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<h1>Add Project</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@project, url: "/projects", method: "post") do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :short_description %>
      <%= f.text_field :short_desc, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.submit "Add Project", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

app/views/test_pages/about.html.erb
<% provide(:title, "About") %>

app/views/test_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>
<h3>Patrick Roxas</h3>
<p>
  Mobile: +63 909 814 5684
  <br>
  Email: patrick@caritax.com
  <br>
  Landline: +63 2 359 2128


</p>

app/views/test_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Welcome</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% @ngos.each do |ngo| %>
      <div class="panel panel-default">
        <div class="panel-body">
          <h5><%= ngo.name %></h5>
          <%= button_to 'Show', ngo, class:"btn btn-sm btn-primary", method: :get %>
        </div>
      </div>
    <% end %>
  </div>  
</div>